package models

// SchemaModels is shared by startup and the offline migration utility.
func SchemaModels() []any {
	return []any{&UploadAsset{}, &UploadReference{}, &TaskClaim{}, &RequestWindow{},
		&User{},
		&EmailCode{},
		&UserPreference{},
		&UserSetting{},
		&AgentToken{},
		&AgentAuditLog{},
		&AgentSuggestion{},
		&Notification{},
		&ChatSession{},
		&ChatMessage{},
		&AssistantUsage{},
		&AssistantLease{},
		&VideoPlatformBudget{},
		&Family{},
		&FamilyMember{},
		&FamilyInvitation{},
		&FamilyPlanItem{},
		&FamilyShoppingItem{},
		&FamilyShoppingCheck{},
		&DishDeleteRequest{},
		&FoodJournalEntry{},
		&HealthDayConfirmation{}, &HealthMealOmission{}, &HealthPlanItem{},
		&HealthProfile{}, &HealthProfileVersion{},
		&HealthDraftUsage{}, &HealthJournalBatch{},
		&NutritionFood{}, &NutritionCatalogFood{},
		&Dish{},
		&MealRecord{},
		&Favorite{},
		&Quote{},
		&Achievement{},
		&UserAchievement{},
		&AchievementEvent{},
		&BlindBox{},
		&Holiday{},
		&Setting{},
		&DayRating{},
		&ShoppingCheck{},
		&HomeInventory{},
		&ShoppingItemCategory{},
		&BehaviorEvent{},
	}
}
